### PR TITLE
A tiny bit of refactoring and some more status updates

### PR DESCRIPTION
**Pull request by obra**
I got irked that the app looked "stuck" while it was waiting on geolocation and hauling down the big sensor list ;)

### CODE REVIEW

**Comment by obra** [comment]
Crap. I screwed up my rebase. But I suppose I should wait until you merge in the updated version of the debug info before I tweak it further.

**Comment by skalnik** [comment]
> Crap. I screwed up my rebase. But I suppose I should wait until you merge in the updated version of the debug info before I tweak it further.

It's all merged! Sorry for stepping on toes 😅 Seems like we raced each other here.

**Comment by obra** [comment]
*grin*

**Comment by obra** [comment]
(pushed up my changes)

**Pull request merged**
