### PR TITLE
Make the AQI number gigantic

### PR DESCRIPTION
**Pull request by obra**
Along the way, add a link to an explanation of what kinds of AQI corrections exist and which one we're using. 

Also fixes a bug where we wouldn't clear the previous body class when refreshing the page.

### CODE REVIEW

**Comment by obra** [comment]
old: 
image

new
image

**Comment by obra** [comment]
@skalnik If you're around, what's your take on these two PRs - I've got other work I'm procrastinating and would be happy to keep iterating :)

**Comment by skalnik** [comment]
@obra I'm checking this one out right now and fixing up some styling! 😅 Sorry for the delay

**Comment by obra** [comment]
On Fri, Sep 11, 2020, at 7:35 PM, Mike Skalnik wrote:
> 

> @obra <https://github.com/obra> I'm checking this one out right now and fixing up some styling! 😅 Sorry for the delay


Don't sweat it! I hope the dentist wasn't too traumatic.

**Comment by skalnik** [comment]
Overall this is great. I moved the sizing down a tad using `em` instead of `vw` so that it doesn't get super-sized when wide, since that lead to the emoji ending up blurry.

Before:
Screen Shot 2020-09-11 at 7 40 07 PM

After:
Screen Shot 2020-09-11 at 7 39 45 PM

And still remains about the same on iOS:

Screen Shot 2020-09-11 at 7 42 22 PM

I also fixed up the AQandU article link which was broken. I *think* it may change anytime they update the article? I wonder if we can find a stable URL for that.

**Comment by obra** [comment]
*sob* I thought we finally lived in the future where color emoji fonts were SVG.

**Comment by skalnik** [comment]
> _sob_ I thought we finally lived in the future where color emoji fonts were SVG.

Same 😞

**Comment by obra** [comment]
Hm. On my XS, it's now -too- big. Well, the emoji is on its own line. Which is fine for now, really.
So yeah. LGTM

**Comment by skalnik** [comment]
> Hm. On my XS, it's now -too- big. Well, the emoji is on its own line. Which is fine for now, really.

Ooh, interesting! I went ahead and made it pick the minimum between the `25vw` along with the `10em` size. Hopefully that fixes that.

**Comment by obra** [comment]
Yes. Confirmed fixed on my XS

**Pull request merged**
