### PR TITLE
More style updates

### PR DESCRIPTION
**Pull request by skalnik**
Style updates are nonstop. I added a small amount of `padding` on the main container so that the new descriptors don't hit the edges.

Before:
Screen Shot 2020-09-11 at 9 11 24 PM

After:
Screen Shot 2020-09-11 at 9 11 43 PM

### CODE REVIEW

**Comment by skalnik** [comment]
I simplified the footer too. I figure we already have links to PurpleAir and GitHub, so we don't need additional ones, but perhaps that's too hasty?

Screen Shot 2020-09-11 at 9 18 50 PM

**Comment by obra** [comment]
100% agree on the padding. Thanks for beating me to it.  I feel like we do want explicit links to GitHub and PurpleAir.

**Comment by skalnik** [comment]
Cool, I went ahead and re-added those links.

I also did some small markup changes:

1. I replaced `<b>` with `<strong>`. Functionally they're the same, but `<strong>` is preferred since it denotes "strong emphasis" over `b` which just denotes "bold" and HTML isn't supposed to specifically denote appearance. How much this actually matters in use, I'm unsure, but it's the better practice from my understanding
2. I adjusted the indentation.

**Comment by obra** [comment]
How about 
image

**Comment by obra** [comment]
(Sorry, was off prototyping. I hear you on my horrible gen-x html use of <B> instead of strong ;) Keep hassling me if I keep doing it.

**Comment by skalnik** [comment]
I like that! Seems both shorter but retains all the link!

**Comment by obra** [comment]
```
        Made with &#10084;&#65039; by <a href="https://skalnik.com">@skalnik</a> &amp; <a href="https://github.com/skalnik/aqi-wtf/graphs/contributors">friends</a> &bull; <a href="https://github.com/skalnik/aqi-wtf/">Code</a> &bull; <a href="https://purpleair.com">Data</a> &bull; <a href="/privacy.html">Privacy</a>
```

**Comment by skalnik** [comment]
I'm always happy to keep hassling, but I gotta notice and remember myself!

**Comment by obra** [comment]
Looks great.

**Pull request merged**
