### PR TITLE
Fix iOS home bar and footer overlap

### LINKED ISSUE #33: on iOS when launched from homescreen, the credits are covered by system UI
We might want to add an em of padding underneath or something.

image

### PR DESCRIPTION
**Pull request by skalnik**
Another attempt to solve the bug in https://github.com/skalnik/aqi-wtf/issues/33 where the iOS home bar and footer overlap.

---

Closes https://github.com/skalnik/aqi-wtf/issues/33

### CODE REVIEW

**Comment by skalnik** [comment]
Hm, no dice. https://dev.to/marionauta/avoid-notches-in-your-pwa-with-just-css-al7 does seem to indicate I'm on the right path though.

**Comment by skalnik** [comment]
The footer no longer overlaps! However, the notch cuts into the text when you have a phone sideways now 😅
IMG_5600

The notch in portrait also remains black. I guess we have no control over that ☹

**Comment by obra** [comment]
Tested on an XS running current release iOS. Totally reasonable for me.

(I wouldn't worry too much about the notch cutting into text. I think we want to play with text size and position more anyway.)

**Comment by skalnik** [comment]
Then I guess this is good to go. We can definitely futz with the spacing around the edges a bit more in the future 👍

I'll merge this now and I'll open a new issue for the notch cutting into the text to dig into separately. Two steps forward, one step back I suppose.

**Pull request merged**
